
[light]
position = [-1, 4, -1]
intensity = 1.1

[[entities]]
type = "sphere"
position = [0, 0, 4]
radius = 2
material = { colour = [1, 1, 0] }

[[entities]]
type = "sphere"
position = [1, 0.5, 3]
radius = 1.5
material = { colour = [1, 0, 1] }
